### ISSUE TITLE
"undefined is not a function" when subscribing to a list of droplets

### ISSUE THREAD

**Issue by marcmascarell** [pjpimentel/dots#17]
Hi,

I'm suddenly getting an error with the latest version `2.2.0` on a code that was running in production normally. It is a simplified version.

```js
dots.Droplet
        .list(0, 5)
        .subscribe(
            (response : any) => {},
            (err: Error) => {
                console.log('ERROR', err.message)
            }
        );
```

`ERROR undefined is not a function`

Any ideas?

**Comment by marcmascarell** [comment]
Here you got the stacktrace:

```
ERROR TypeError: undefined is not a function
    at Array.every (<anonymous>)
    at Object.isCollection (node_modules\dots-wrapper\dist\common\type.guards.js:453:21)
    at TapSubscriber._tapNext (node_modules\dots-wrapper\dist\common\endpoint.js:54:32)
    at TapSubscriber._next (node_modules\rxjs\internal\operators\tap.js:56:27)
    at TapSubscriber.Subscriber.next (node_modules\rxjs\internal\Subscriber.js:64:18)
    at MapSubscriber._next (node_modules\rxjs\internal\operators\map.js:52:26)
    at MapSubscriber.Subscriber.next (node_modules\rxjs\internal\Subscriber.js:64:18)
    at MapSubscriber._next (node_modules\rxjs\internal\operators\map.js:52:26)
    at MapSubscriber.Subscriber.next (node_modules\rxjs\internal\Subscriber.js:64:18)
    at node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by pjpimentel** [comment]
@marcmascarell 
I'm deploying a hotfix to beta version 2.1.13-0, could you try install and test  it?

`npm install --save dots-wrapper@beta`

Today, the beta master has same code from master branch (except this fix).

https://github.com/pjpimentel/dots/pull/18/commits/6e7750b9ccd603cbd7da34b75d483361f96d5698

**Comment by marcmascarell** [comment]
It works fine! Thanks!
